---
# file: base.yaml
# Contains basic setup tasks for Ubuntu
- hosts: all
  become: true
  vars_prompt:
    - name: "logwatch_email"
      prompt: "Enter email address for logwatch email delivery"
      private: "no"
  vars:
    deploy_user_name: adminlocal
    deploy_user_ssh_key: ansible.id_rsa
  tasks:
    # APT
    - name: update APT package cache
      apt: update_cache=yes cache_valid_time=3600
      tags: apt

      # value of state must be one of: absent, build-dep, fixed, latest, present
    - name: install aptitude
      apt: name=aptitude state=latest
      tags: apt

    - name: upgrade APT to the latest packages
      apt: upgrade=safe
      tags: apt

    - name: install core packages
      apt: 
        name: ['nano', 'wget', 'curl', 'p7zip-full']
        state: latest
        install_recommends: no
      tags: apt

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      tags: apt
    
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      tags: apt

    # Logwatch
    - name: Set up Postfix to relay mail
      debconf: name=postfix
               question='{{ item.question }}'
               value='{{ item.value }}'
               vtype='{{ item.vtype }}'
      with_items:
        - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
        - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }
      tags: logwatch

    - name: Email log summary daily
      lineinfile: dest=/etc/cron.daily/00logwatch
                  regexp="^/usr/sbin/logwatch"
                  line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
                  state=present create=yes
      tags: logwatch