# file: roles/k3s/tasks/join-cluster.yaml
# Joins an existing cluster using a master_node address and token

- name: joining master node {{ ansible_fqdn }}
  debug: var=k3s_server_address
  tags: k3s, join-cluster, cluster

- name: using token {{ k3s_cluster_token }}
  debug: var=k3s_cluster_token
  tags: k3s, join-cluster, cluster

# thanks to https://stackoverflow.com/a/47449216/322358
- name: check we can connect to master on 6443
  command: 
    warn: false
    cmd: curl --insecure {{ k3s_server_address }}
  register: cmd_res
  retries: 5
  delay: 10
  until: cmd_res.stdout.find("apiVersion") >= 1
  become: no
  tags: k3s, join-cluster, cluster

- name: install k3s (join existing cluster)
  raw: |
    export K3S_KUBECONFIG_MODE="644"; \
    export INSTALL_K3S_EXEC="server --server {{ k3s_server_address }}"; \
    export K3S_TOKEN="{{ k3s_cluster_token }}"; \
    curl -sfL https://get.k3s.io | sh -
  become: yes
  tags: k3s, join-cluster, cluster
  notify: setup kubeconfig
