---
# file: roles/k3s/tasks/wireguard.yaml
# Sets up pre-requisites for Wireguard VPN

- name: add wireguard ppa
  apt_repository:
    repo: ppa:wireguard/wireguard
    state: present
  tags: apt, wireguard

- name: install wireguard
  apt:
    name: wireguard
    state: latest
    update_cache: yes
  tags: apt, wireguard

- name: test wireguard kernel module loaded
  modprobe:
    name: wireguard
    state: present
  tags: wireguard