---
# file: roles/kubeadm/tasks/cluster-init-cni.yaml
# Installs a Container Network Interface
# have chosen to go with the standard calico, flannel, canal options

- name: obtain latest calico manifest
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: deploy/calico.yaml
    mode: '0640'
    force: yes
  tags: cluster, cni
  become: no
  delegate_to: "localhost"

- name: switch default 192.168.0.0/16 for {{ CIDR }}
  shell:
     cmd: sed -i -e "s?192.168.0.0/16?{{ CIDR }}?g" deploy/calico.yaml
     warn: false
  become: no
  tags: cluster, cni
  delegate_to: "localhost"

- name: copy across manifest
  copy:
    src: deploy/calico.yaml
    dest: ~/calico.yaml
  become: no
  tags: cluster, cni

- name: apply vanilla calico manifest
  command: kubectl apply -f ~/calico.yaml
  become: no
  tags: cluster, cni