---
# file: roles/base/tasks/main.yaml
# Contains basic setup tasks for Ubuntu

# APT
- include: apt.yaml

# Logwatch
- include: logwatch.yaml

# Users
- include: users.yaml

# SSH and Firewall hardening
- include: ssh.yaml
- include: firewall.yaml

# Avahi service discovery (optional)
- include: avahi.yaml
  when: enable_avahi is undefined or enable_avahi|bool is true