---
# file: roles/base/tasks/main.yaml
# Contains basic setup tasks for Ubuntu

# Hostname
- name: Set hostname to inventory hostname
  hostname: name={{inventory_hostname}}

# APT
- include: apt.yaml

# Logwatch
- include: logwatch.yaml
  when: logwatch_email is defined and logwatch_email|length > 0

# Users
- include: users.yaml

# SSH and Firewall hardening
- include: ssh.yaml
- include: firewall.yaml

# Avahi service discovery (optional)
- include: avahi.yaml
  when: enable_avahi is undefined or enable_avahi|bool is true