---
# file: roles/base/tasks/users.yaml
# Sets up initial admin user

- name: create admin user {{ deploy_user_name }}
  user:
    name: "{{ deploy_user_name }}"
    shell: /bin/bash
    append: yes
    groups: sudo
  tags: user

- name: add authorized_key
  authorized_key:
    user: "{{ deploy_user_name }}"
    state: present
    key: "{{ lookup('file', '{{ deploy_user_ssh_key }}') }}"
  tags: user, ssh